### ISSUE TITLE
Standup: 6 April 2023

### ISSUE THREAD

**Issue by vladmet1** [ISUCT/3-147-42-January-May-2023#13]
Что делал:
Что делаю:
Что буду делать:
Что блокирует работу:

**Comment by s1max** [comment]
Что делал: с коллегами @anCreny @Bugfasov @dmitriy-malakhov пришли к компромиссу, как должен визуально выглядеть опросник и начали работу (сделано ~70%).
Что делаю: доделываем визуальную часть опросника
Что буду делать: по готовности визуала соединим с бэкэндом
