### ISSUE TITLE
Standup: 2 March 2023

### ISSUE THREAD

**Issue by the-homeless-god** [ISUCT/3-147-42-January-May-2023#3]
Что делал:
Что делаю:
Что буду делать:
Что блокирует работу:

**Comment by s1max** [comment]
Что делал/делаю:
1.  Начал читать "Блистательный Agile".
2.  Попробовал  составить дорожные карты для раздела "Опросник".
3.  Перераспределил между разработчиками некоторые роли и обязанности.
4. Контролировал ход работы.
Что буду делать:
Продолжу читать, изучать гит, опишу цели и задачи до следующего дедлайна.

**Comment by vladmet1** [comment]
Стал менеджером команды "Библиотека компонентов"
1. Создал отдельный репозиторий для реализации проекта
2. Отправил инвайты участникам, распределил роли
3. Написал первые задачи для выполнения

**Comment by LenaNaumova** [comment]
Стала менеджером в команде Assets по картинкам с нейронки

1. Создали чат с командой
2. Распределили роли
3. Все скачали и установили нейронку
4. Разобрались как работает
5. Ждём запросы от других групп на создание картинок

**Comment by markru37** [comment]
1 March 2023:
Что делал:
* Создал начальный темплейт для UI-библиотеки
* Настроили с @SunM1sty начало Storybook'а
Ссылка на репу - https://github.com/SunM1sty/UI-Kit
Что делаю: 
* В процессе поиска информации по созданию UI-библиотеки
* Ковыряю Storybook
Что буду делать: 
* Продолжение текущих задач

**Comment by anihsort** [comment]
1. Начала читать статьи, о том как правильно создавать макеты
2. Изучала материал по типографике и шрифтам 
3. Смотрела примеры интерфейсов и прототипов, сделанных в фигме
4. Вспоминала работу с инструментами фигмы
Планирую подробнее изучить основные элементы интерфейса и создать самой несколько для отработки полученных знаний

**Comment by progonskaij** [comment]
разобрала объекты 1с такие как
1. справочники
2.документы 
3. отчеты
планирую разобрать регистры  регистры накоплений и регистры сведений. Также планирую почитать о хранении данных в 1с.

**Comment by Eelizaveta** [comment]
Что делал:
- стала менеджером проекта Аналитики
- создала группу в тг
- написала текст для опросника
Что делаю:
- начали распределять обязанности
- начала читать Блистательный Agile

Что буду делать:
- напишу задачи для выполнения и дорожные карты
- создам репозиторий для проекта
- доделаю текст для опросника

**Comment by DustofTimeYT** [comment]
Что делал: Вступил в созданную группу в тг. Стал ответственным в области 3D моделей
Что делаю/буду делать: Изучать вопрос о необходимых моделях

**Comment by Bugfasov** [comment]
что делал:
написал текст для опросника
попытался разобраться в бэке
вступил в беседы по опроснику и игре
сделал первые наработки по с.жету
начал изучать функционал chat gbt(зарегался на немецкую симку)
что делаю: продолжаю развитие вышеперечисленных тем, пытаюсь организовать людей на front 
что буду делать: 
доведу опросник и сюжет до ума
что блокирует работу:
понял, что нужно делегировать бэк на других людей, потому что сам не успею сделать в срок и сильно застопорю проект

**Comment by PavlovYuri** [comment]
Что делал: поизучал docker, подключился к PostgreSQL
Что делаю: начало написания сервиса + необходимо скоординировать действия
Что буду делать: писать дальше
Что блокирует работу: особо ничего, правда есть другие небольшие дела

**Comment by SanyaKirilv** [comment]
Что делал/Что делаю: проект по работе
Что буду делать: Ждать концепта игры и основных механик
Что блокирует работу: Отсутствие концепта игры и основных механик

**Comment by Borshecs** [comment]
Что делал: сортировал и выбирал информацию для изучения.
Что делаю: изучаю пирамиду тестирования + тест кейсы
Что буду делать: посмотрю что такое и с чем есть Cypress/Selenium/Playwright/NutTree.js
Что блокирует работу: другие делишки, но всё под контролем, наверное

**Comment by SunM1sty** [comment]
1-2 March 2023:
Что делал:

Создал начальный темплейт для UI-библиотеки
Настроили с @markru37 начало Storybook'а
Ссылка на репу - https://github.com/isuct-ui-components/web-ui-components
Настроил линтер и приттиер для проекта

Что делаю:
Изучаю настройку вебпака под проект
В процессе поиска информации по созданию UI-библиотеки
Ковыряю Storybook

**Comment by San1k-02** [comment]
Что делал/делаю: определил цель аналитики, вспоминаю тестирование с помощью Selenium
Что буду делать: готовиться к непосредственным работам над проектами

**Comment by Auzet** [comment]
Что делал/делаю:
Установил stable diffusion, разобрался в основных фичах
Нарисовал скелет главной страницы сайта-визитки
Проанализировал предложенный командой ui-kit

Что буду делать:
Помогать в работе с ui-kit'ом
Создавать дизайн сайта

Что блокирует работу:
Неизвестна тема разрабатываемой игры, как следствие невозможно создавать тематический дизайн

**Comment by Bugfasov** [comment]
Что делал/делаю:
Дописал вопросы для опросника, разбили их на 2 типа
Разобрался с структурой сайта опросника
Начал его разработку
Что буду делать: 
Делать сайт опросник
Делать сюжет
Что блокирует: 
Не могу делать сюжет, пока нет опросника

**Comment by lapshal** [comment]
Что делал/Что делаю:
1.скачал,установил и настроил нейронку(stable diffusion),
2.поэксперементировал с ней  
3.разобрался в функциях данной нейронки
Что буду делать:
1.разбираться с более сложными фичами и функциями
2.ждать указаний менеджеров

**Comment by DustofTimeYT** [comment]
Что делал/Что делаю:
Продолжаю изучать вопрос о необходимых моделях,
Начинаю создание персонажа
Что буду делать:
Закончу создание персонажа,
Продолжу создание необходимых моделей

**Comment by Greenprize** [comment]
Что делал:
- > Повторял основные концепции построения текста
- > Изучил основы создания наратива
- > Изучил основные 5 жанров произведений в худ литературе

Что буду делать:
- > Продолжу углублять в основные жанры худ литераты и типологии текстов
- > Изучу построенние многожанровых произведений

**Comment by markru37** [comment]
Что делал/Что делаю:
1. Пофиксили баги с запуском storybook
2. Создали компонент кнопки, прикрутил несколько режимов для отображения кнопки
3. Передвинули миксины
Что буду делать:
1. Допилить другие режимы для компоненты кнопки
2.  Создать другую компоненту и добавить в неё режимы(simple input, toggle, checkbox, image, container на выбор)
-------
Всё это - совместно с @SunM1sty

**Comment by Bugfasov** [comment]
Что делал/Что делаю:
Писал/Пишу сайт опросник
Определились с формой
Разбираюсь в Json и rest api
