### ISSUE TITLE
Распределиться по группам менеджерам

### ISSUE THREAD

**Issue by Dasfor** [ISUCT/3-147-42-January-May-2023#6]
Написать в комментах какой менеджер за какую группу отвечает: Библиотека компонентов, Аналитика, Игра, Опросы, Картинки с нейросеток

**Comment by vladmet1** [comment]
Аналитика

**Comment by Dasfor** [comment]
Игра

**Comment by LenaNaumova** [comment]
Картинки с нейросеток

**Comment by s1max** [comment]
Опросы

**Comment by Eelizaveta** [comment]
Аналитика
