### ISSUE TITLE
Пройти опрос по выбору жанра игры

### ISSUE THREAD

**Issue by Dasfor** [ISUCT/3-147-42-January-May-2023#7]
Можно выбрать несколько вариантов, потом выберем тот, что набрал наибольшее количество голосов
https://docs.google.com/forms/d/e/1FAIpQLSc_66Klt-k3qPOkZSzgmJDgcH-5vQ3tVG5n_RjJgMytDTPDew/viewform?usp=sf_link

**Comment by LenaNaumova** [comment]
оки
